services:
  postgres:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    image: postgres:${COMPOSE_PROJECT_NAME}
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGSSLMODE: disable
    command: ["postgres", "-c", "ssl=off"] # supply a certificate to enable
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 20s
      retries: 5
      start_period: 30s

  redis:
    build:
      context: ./.docker/redis
      dockerfile: Dockerfile
    image: redis:${COMPOSE_PROJECT_NAME}
    container_name: redis
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME}_postgres_data
