[server]
host = "0.0.0.0"
port = 3000

[database]
min_open_conns = 2
max_open_conns = 5
max_conn_lifetime = 60
max_idle_lifetime = 30
health_check_period = 5
max_retries = 3
retry_delay = 1

[logging]
level = "info"